### ISSUE TITLE
FE - Backoffice/Dashboard - Bootcamps

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/ValidadorBootcamp-frontend#12]
### Descripción

-  Crear el mockup del backoffice en la vista bootcamps (CRUD de bootcamps)
-  Crear los componentes del administrador de bootcamps siguiendo la arquitectura del proyecto (Container, View)

Estructura del proyecto:

```
src/
   feature/
         bootcamps/
                         /admin  
                                  admin.bootcamps.container.tsx
                                  admin.bootcamps.view.container.tsx
```

### Criterios de aceptación

- Evidenciar el mockup en el repositorio (archivo .excalidraw)
- Implementar el componente de acuerdo al mockup sin perder el alcance existente.

**Comment by Orliluq** [comment]
![Bootcamps-Dashboard](https://github.com/Trycatch-tv/ValidadorBootcamp-frontend/assets/122529721/2a50a4fd-ac9b-49a2-a4e3-9ffecb250d8a)
Ajustando según requerimientos, revisar.
