### ISSUE TITLE
FE - Configurar Cypress

### ISSUE THREAD

**Issue by judlup** [Trycatch-tv/ValidadorBootcamp-frontend#19]
### Descripción

Configurar Cypress en el proyecto teniendo en cuenta:

- Implementar la configuración básica de Cypress en el proyecto

Estructura del proyecto:

### Criterios de aceptación

- Implementar una prueba utilizando Cypress para comprobar el funcionamiento del componente Home en ejecución.
- Configurar el script en package.json para ejecutar las pruebas

### Links 

- [Librearía Cypress](https://www.cypress.io/)

**Comment by Orliluq** [comment]
Configuración inicial según documentación lista!!



![Image](https://github.com/Trycatch-tv/ValidadorBootcamp-frontend/assets/122529721/6f519210-ab28-4fad-b9b2-677bc1bd59a1)
